import {StyleSheet} from 'react-native';
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import colors from '../Assets/colors/colors';
export default StyleSheet.create({
  loader: {
    zIndex: 100,
    position: 'absolute',
    height: hp('100%'), 
    width: wp('100%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  whiteButton: {
    marginHorizontal: 24,
    marginVertical: 10,
    borderRadius: 40,
    justifyContent: 'center',
    backgroundColor: colors.white,
    height: 50,
  },
  blueButton: {
    marginHorizontal: 24,
    marginVertical: 10,
    borderRadius: 40,
    backgroundColor: colors.primary,
    height: 52,
    justifyContent: 'center',
  },
  transparentButton: {
    marginHorizontal: 24,
    marginVertical: 20,
    borderRadius: 40,
    borderWidth: 1,
    height: 52,
    borderColor: colors.white,
  },
  borderlessButton: {
    justifyContent: 'center',
    marginHorizontal: 24,
    marginVertical: 10,
    height: 52,
  },
  blueButtonText: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    color: colors.primary,
  },
  whiteButtonText: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical:'center',
    color: colors.white,
  },
  titleText: {
    // fontFamily: 'Axiforma-Regular',
    // fontWeight: '900',
    fontSize: 32,
    color: colors.textInput,
    marginLeft: 18,
    marginBottom: 10,
  },
  titleText2: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '900',
    fontSize: 24,
    color: colors.textInput,
    marginLeft: 18,
    marginTop: 6,
    marginBottom: 12,
  },
  subtitleText: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    color: '#828282',
    marginLeft: 18,
    marginBottom: 25,
  },
  subtitleText2: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    color: '#828282',
    marginLeft: 18,
  },
  label: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 14,
    marginLeft: 18,
    marginTop: 20,
    color: '#828282',
  },
  textfield1: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    marginHorizontal: 15,
    paddingLeft:15,
    height: 45,
    borderWidth: 1,
    color: colors.textInput,
    borderColor: colors.primary,
    borderRadius: 6,
    marginTop: 5,
  },
  textfield2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent:'space-between',
    paddingHorizontal:15,
    backgroundColor: '#F2F2F2',
    marginHorizontal: 15,
    height: 45,
    borderRadius: 6,
    marginTop: 5,
  },
  slider: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  minus: {
    marginLeft: 0,
  },
  textfieldText: {
    flex: 9,
    // fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    color: colors.textInput,
  },
  picker: {
    fontFamily: 'Axiforma-Regular',
    fontWeight: '400',
    fontSize: 16,
    backgroundColor: '#F2F2F2',
    color: colors.textInput,
  },
  phoneInput: {
    backgroundColor: '#F2F2F2',
    width: 330,
    color: colors.textInput,
    marginHorizontal: 15,
    height: 45,
    borderRadius: 6,
    marginTop: 5,
  },
  sheetContainer:{
      paddingBottom:20,
      borderWidth:1,
      borderColor:'grey',
      borderRadius:10
  },
  checkIcon:{
      position:'absolute',
      right:30,
      top:15,
      paddingTop:1,
      backgroundColor:'#3ce630',
   borderRadius:10,
   borderWidth:1,
  borderColor:'grey'
},
  line:{
      marginTop:5,
      backgroundColor:'grey',
      height:8,
      width:80,
      alignSelf:'center',
      borderRadius:5,
  },
  title:{
      textAlign:'center',
      paddingVertical:20,
      fontFamily:'Axiforma-Regular',
      fontSize:22,
      color : "black"
  },
  sheet1:{
      justifyContent:'space-evenly',
  },
  itemWrapper:{
      alignItems:'center',
      paddingVertical:15,
  },
  sheetItem:{
      fontFamily:'Axiforma-Regular',
      fontSize:18,
      color : "black"
  },
});
